package dcms;

/**
* dcms/DCMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcms.idl
* Friday, June 16, 2017 5:25:01 o'clock PM EDT
*/

public final class DCMSHolder implements org.omg.CORBA.portable.Streamable
{
  public dcms.DCMS value = null;

  public DCMSHolder ()
  {
  }

  public DCMSHolder (dcms.DCMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dcms.DCMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dcms.DCMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dcms.DCMSHelper.type ();
  }

}
