package dcms;


/**
* dcms/DCMSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcms.idl
* Friday, June 16, 2017 5:25:01 o'clock PM EDT
*/

public abstract class DCMSPOA extends org.omg.PortableServer.Servant
 implements dcms.DCMSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("transferReservation", new java.lang.Integer (0));
    _methods.put ("getCount", new java.lang.Integer (1));
    _methods.put ("editRecord", new java.lang.Integer (2));
    _methods.put ("book", new java.lang.Integer (3));
    _methods.put ("getAllInfo", new java.lang.Integer (4));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // dcms/DCMS/transferReservation
       {
         int passengerID = in.read_long ();
         String current = in.read_string ();
         String other = in.read_string ();
         dcms.Result $result = null;
         $result = this.transferReservation (passengerID, current, other);
         out = $rh.createReply();
         dcms.ResultHelper.write (out, $result);
         break;
       }

       case 1:  // dcms/DCMS/getCount
       {
         String recordType = in.read_string ();
         String $result = null;
         $result = this.getCount (recordType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // dcms/DCMS/editRecord
       {
         int recordID = in.read_long ();
         String fieldName = in.read_string ();
         String newValue = in.read_string ();
         dcms.Result $result = null;
         $result = this.editRecord (recordID, fieldName, newValue);
         out = $rh.createReply();
         dcms.ResultHelper.write (out, $result);
         break;
       }

       case 3:  // dcms/DCMS/book
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phone = in.read_string ();
         String des = in.read_string ();
         String date = in.read_string ();
         String tClass = in.read_string ();
         dcms.Result $result = null;
         $result = this.book (firstName, lastName, address, phone, des, date, tClass);
         out = $rh.createReply();
         dcms.ResultHelper.write (out, $result);
         break;
       }

       case 4:  // dcms/DCMS/getAllInfo
       {
         String $result = null;
         $result = this.getAllInfo ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:dcms/DCMS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DCMS _this() 
  {
    return DCMSHelper.narrow(
    super._this_object());
  }

  public DCMS _this(org.omg.CORBA.ORB orb) 
  {
    return DCMSHelper.narrow(
    super._this_object(orb));
  }


} // class DCMSPOA
