package dcms;


/**
* dcms/DCMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcms.idl
* Friday, June 16, 2017 5:25:01 o'clock PM EDT
*/

public interface DCMS extends DCMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DCMS
