package dcms;


/**
* dcms/DCMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcms.idl
* Friday, June 16, 2017 5:25:01 o'clock PM EDT
*/

public interface DCMSOperations 
{
  dcms.Result transferReservation (int passengerID, String current, String other);
  String getCount (String recordType);
  dcms.Result editRecord (int recordID, String fieldName, String newValue);
  dcms.Result book (String firstName, String lastName, String address, String phone, String des, String date, String tClass);
  String getAllInfo ();
} // interface DCMSOperations
