package dcms;

/**
* dcms/ResultHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from dcms.idl
* Friday, June 16, 2017 5:25:01 o'clock PM EDT
*/

public final class ResultHolder implements org.omg.CORBA.portable.Streamable
{
  public dcms.Result value = null;

  public ResultHolder ()
  {
  }

  public ResultHolder (dcms.Result initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = dcms.ResultHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    dcms.ResultHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return dcms.ResultHelper.type ();
  }

}
